from datetime import datetime, timezone
import bcrypt
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.core.jwt import create_access_token
from app.db.database import get_db
from app.db.models import Company, InviteToken
from app.schemas.company_auth import (
    CompanyLoginRequest,
    CompanyLoginResponse,
    CompanyOnboardRequest,
    CompanyOnboardResponse,
)

router = APIRouter(
    prefix="/company",
    tags=["Company Authentication"],
)


# =========================================================
# 1. ONBOARD COMPANY WITH ONE-TIME INVITE TOKEN
# =========================================================

@router.post(
    "/onboard",
    response_model=CompanyOnboardResponse,
    status_code=status.HTTP_201_CREATED,
    summary="First-Time Company Registration via Invite Token",
)
def onboard_company(
    payload: CompanyOnboardRequest,
    db: Session = Depends(get_db),
):
    """
    Onboards a new company using the single-use invite token generated by Admin.
    The invite token is burned immediately upon successful registration.
    """
    # 1. Lookup and validate invite token
    token_record = (
        db.query(InviteToken)
        .filter(InviteToken.token == payload.invite_token.strip())
        .first()
    )

    if not token_record:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Invalid invite token. Please request a valid token from Admin.",
        )

    if token_record.is_used:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="This invite token has already been used and cannot be reused.",
        )

    # Timezone-aware expiration check
    current_time = datetime.now(timezone.utc)
    token_expiry = token_record.expires_at
    if token_expiry.tzinfo is None:
        token_expiry = token_expiry.replace(tzinfo=timezone.utc)

    if current_time > token_expiry:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="This invite token has expired. Please request a new token from Admin.",
        )

    # 2. Check for duplicate company ID or email
    existing_company = (
        db.query(Company)
        .filter(
            (Company.company_id == payload.company_id)
            | (Company.email == payload.email)
        )
        .first()
    )
    if existing_company:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Company ID or Email is already registered.",
        )

    # 3. Hash company password
    hashed_password = bcrypt.hashpw(
        payload.password.encode("utf-8"),
        bcrypt.gensalt(),
    ).decode("utf-8")

    # 4. Create and activate company
    new_company = Company(
        company_id=payload.company_id,
        company_name=payload.company_name,
        email=payload.email,
        password_hash=hashed_password,
        status="ACTIVE",
        is_active=True,
        created_at=current_time,
        approved_at=current_time,
    )

    # 5. Burn the token
    token_record.is_used = True
    token_record.used_at = current_time
    token_record.used_by_company_id = payload.company_id

    db.add(new_company)
    db.commit()
    db.refresh(new_company)

    # 6. Issue immediate client token using your core JWT creator
    token = create_access_token(
        company_id=new_company.company_id,
        extra_claims={
            "email": new_company.email,
            "company_name": new_company.company_name,
        },
    )

    return CompanyOnboardResponse(
        status="success",
        message="Company onboarded and activated successfully. Invite token has been burned.",
        company_id=new_company.company_id,
        company_name=new_company.company_name,
        email=new_company.email,
        access_token=token,
        token_type="bearer",
    )


# =========================================================
# 2. STANDARD COMPANY LOGIN (SUBSEQUENT SESSIONS)
# =========================================================

@router.post(
    "/login",
    response_model=CompanyLoginResponse,
)
def company_login(
    payload: CompanyLoginRequest,
    db: Session = Depends(get_db),
):
    """
    Authenticate a company and issue a client JWT.
    Only ACTIVE companies can receive a client token.
    """
    # 1. Find company
    company = (
        db.query(Company)
        .filter(Company.email == payload.email)
        .first()
    )

    if not company:
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password",
        )

    # 2. Check company approval status
    if company.status == "PENDING":
        raise HTTPException(
            status_code=403,
            detail=(
                "Company approval is pending. "
                "Please wait for administrator approval."
            ),
        )

    if company.status == "REJECTED":
        raise HTTPException(
            status_code=403,
            detail=(
                "Company access has been rejected "
                "by the administrator."
            ),
        )

    if company.status != "ACTIVE":
        raise HTTPException(
            status_code=403,
            detail="Company is not active.",
        )

    # 3. Check password configuration
    if not company.password_hash:
        raise HTTPException(
            status_code=500,
            detail="Company password is not configured.",
        )

    # 4. Verify password
    try:
        password_valid = bcrypt.checkpw(
            payload.password.encode("utf-8"),
            company.password_hash.encode("utf-8"),
        )
    except ValueError:
        raise HTTPException(
            status_code=500,
            detail="Invalid company password configuration.",
        )

    if not password_valid:
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password",
        )

    # 5. Create client JWT
    token = create_access_token(
        company_id=company.company_id,
        extra_claims={
            "email": company.email,
            "company_name": company.company_name,
        },
    )

    # 6. Return client token
    return {
        "access_token": token,
        "token_type": "bearer",
        "company_id": company.company_id,
        "company_name": company.company_name,
        "status": company.status,
    }